### ISSUE TITLE
Google wants certificate verification

### ISSUE THREAD

**Issue by dojero** [nidhaloff/deep_translator#1]
* deep_translator version: 1.0.6
* Python version: 3.8.3
* Operating System: Linux

### Google gives warning before response

Request any translation from GoogleTranslate and the response comes back:

Warning: Unverified HTTPS request is being made to host 'translate.google.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn
 
Followed by the translation. So it all works beautifully. At a minimum, I'd like to suppress the warning.

**Comment by nidhaloff** [comment]
Thanks for the feedback. I solved the issue and published a new [release](https://pypi.org/project/deep-translator/1.0.7/) v1.0.7 on pypi

**Comment by dojero** [comment]
Works perfectly now. Very nicely done program.

Thanks.
________________________________
