### ISSUE TITLE
Add Deepl

### ISSUE THREAD

**Issue by Chouchen** [nidhaloff/deep_translator#3]
[Deepl](https://www.deepl.com/translator) should be added to this app to be more awesome!

**Comment by nidhaloff** [comment]
Great idea! Thanks for the suggestion. I don't have much free time at the moment but I will work on this ;)
Alternatively, contributions are always welcome :smile:  
PS: notice that the deep_translator is a **free and unlimited** translation tool. If deepl is not free or provide a limited API, then it can not be integrated here :/

**Comment by mphirke** [comment]
Deepl API requires their pro (paid) plan, although it is unlimited.

**Comment by nidhaloff** [comment]
@mphirke Thanks, I just checked out and you are right. I'm aiming to keep the package free, therefore the deepl paid service doesn't belong here. 

@Chouchen Sorry I can't integrate deepl for these reasons, but maybe it could be developed as an extra tool
