### ISSUE TITLE
Pons translator only returns the first word

### ISSUE THREAD

**Issue by prataffel** [nidhaloff/deep_translator#6]
* deep_translator version: 1.1.3
* Python version: 3.8.5
* Operating System: Linux

### Description

The Pons translator only returns the first word of the translation - even if the first entry of the list of all results contains multiple words.

### What I Did

`deep_translator.PonsTranslator(source='german', target='english').translate('laufen')` returns `'to '` (expected would be 'to run' which is the first entry in the list returned by `deep_translator.PonsTranslator(source='german', target='english').translate('laufen', return_all = True)`).

**Comment by nidhaloff** [comment]
Thanks for noticing this. I will work on fixing it ;)

**Comment by nidhaloff** [comment]
Fixed in the new release == **1.1.4**
